version: 2.1

orbs:
  golangci-lint: neilisaac/golangci-lint@0.0.1

executors:
  go:
    docker:
      - image: circleci/golang:1.14

jobs:
  test:
    executor: go
    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report
      - run: mkdir -p /tmp/test-results
      - run: go test -v -race ./... | go-junit-report > /tmp/test-results/spec.xml
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2
  main:
    jobs:
      - test